// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRfC0GQy-YVA-cdXB5NegcHofM3fVA9qM',
    appId: '1:1005430108140:web:d5906e5a860cdddf2e9ac9',
    messagingSenderId: '1005430108140',
    projectId: 'chatgpt-fyp-project',
    authDomain: 'chatgpt-fyp-project.firebaseapp.com',
    storageBucket: 'chatgpt-fyp-project.appspot.com',
    measurementId: 'G-1XFJ7B41EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJZ5Ez5xd3EGbGGtLi3HcJBQ_QzdlKHnw',
    appId: '1:1005430108140:android:576f626505b35bf62e9ac9',
    messagingSenderId: '1005430108140',
    projectId: 'chatgpt-fyp-project',
    storageBucket: 'chatgpt-fyp-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTVloYqKoDXsPyUWtKxe7z5W2dzkw_rhM',
    appId: '1:1005430108140:ios:3c8982ec37863bdf2e9ac9',
    messagingSenderId: '1005430108140',
    projectId: 'chatgpt-fyp-project',
    storageBucket: 'chatgpt-fyp-project.appspot.com',
    iosBundleId: 'com.example.chatgptApp',
  );
}
